services:
  s3admin:
    image: dpage/pgadmin4:latest

    container_name: 68-s3-admin
    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASS}
    ports:
      - "5050:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
